metrics:
  jshead:
    - js/jquery.min.js
    - js/d3.v3.min.js
    - js/metrics-graphics.min.js
  css:
    - css/metrics-graphics.css
  cdn:
    jshead:
      - http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js
      - http://d3js.org/d3.v3.min.js
      - http://mozilla.github.io/metrics-graphics/js/metrics-graphics.min.js
    css:
      - http://mozilla.github.io/metrics-graphics/css/metrics-graphics.css
